# Generated by Django 3.1.7 on 2021-03-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiretuber',
            name='first_name',
            field=models.CharField(default='first_name', max_length=100),
        ),
        migrations.AddField(
            model_name='hiretuber',
            name='last_name',
            field=models.CharField(default='last_name', max_length=100),
        ),
    ]
