# Generated by Django 3.1.7 on 2021-03-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0002_auto_20210322_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
