# Generated by Django 3.1.7 on 2021-04-13 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hiretubers', '0003_auto_20210325_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiretuber',
            name='sender',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
         migrations.AddField(
            model_name='hiretuber',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('received', 'received'), ('delivered', 'delivered'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='delivered', max_length=20),
        ),
      
        migrations.AlterField(
            model_name='hiretuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
