# Generated by Django 3.1.7 on 2021-04-13 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hiretubers', '0004_auto_20210413_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiretuber',
            name='receiver',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to=settings.AUTH_USER_MODEL),
        ),
       
        migrations.AlterField(
            model_name='hiretuber',
            name='sender',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
