# Generated by Django 3.1.7 on 2021-03-25 04:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='heading..', max_length=100)),
                ('photo', models.ImageField(upload_to='media/webpages/%Y/%m/')),
                ('description', ckeditor.fields.RichTextField(help_text='write description here...')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
