# Generated by Django 3.1.7 on 2021-04-14 09:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210408_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuberprofile',
            name='announcement',
            field=ckeditor.fields.RichTextField(default='No announcement'),
        ),
        migrations.AlterField(
            model_name='tuberprofile',
            name='description',
            field=ckeditor.fields.RichTextField(default='No descriptions'),
        ),
    ]
