# Generated by Django 3.1.7 on 2021-04-15 08:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210414_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=accounts.models.get_default_profile_image, upload_to=accounts.models.get_profile_image_path),
        ),
        migrations.AlterField(
            model_name='tuberprofile',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tuberprofile',
            name='camera_type',
            field=models.CharField(blank=True, choices=[('canon', 'canon'), ('nicon', 'nicon'), ('sony', 'sony'), ('red', 'red'), ('fuji', 'fuji'), ('panasonic', 'panasonic'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tuberprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('code', 'code'), ('mobile_review', 'mobile_review'), ('vlogs', 'vlogs'), ('comedy', 'comedy'), ('gaming', 'gaming'), ('film_making', 'film_making'), ('cooking', 'cooking')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tuberprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tuberprofile',
            name='crew',
            field=models.CharField(blank=True, choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tuberprofile',
            name='height',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tuberprofile',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tuberprofile',
            name='subs_count',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='tuberprofile',
            name='video_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
