# Generated by Django 3.1.7 on 2021-03-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_email', models.EmailField(max_length=254)),
                ('header_phone', models.IntegerField()),
                ('footer_fb_link', models.CharField(blank=True, max_length=100)),
                ('footer_insta_link', models.CharField(blank=True, max_length=100)),
                ('footer_twitter_link', models.CharField(blank=True, max_length=100)),
                ('footer_youtube_link', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
