# Generated by Django 3.1.7 on 2021-03-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='footer_fb_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='footer_insta_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='footer_twitter_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='footer_youtube_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='header_phone',
        ),
    ]
