# Generated by Django 3.1.7 on 2021-03-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0002_auto_20210323_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactinfo',
        ),
    ]
