# Generated by Django 3.1.7 on 2021-03-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0004_contactinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='ceated_date',
            new_name='created_date',
        ),
    ]
