# Generated by Django 3.1.7 on 2021-03-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0006_auto_20210324_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='footer_fb_link',
            field=models.CharField(blank=True, default='https://www.facebook.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='footer_insta_link',
            field=models.CharField(blank=True, default='https://www.instagram.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='footer_twitter_link',
            field=models.CharField(blank=True, default='https://www.twitter.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='footer_youtube_link',
            field=models.CharField(blank=True, default='https://www.youtube.com/', max_length=100),
        ),
    ]
